version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data  # dataset BigQuery
    # loader: bigquery    # facultatif
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "sales of Greenweez / we have one row per product_id found in each orders_id"
      - name: product
        identifier: raw_gz_product
        description: "product of Greenweez / we have one row per product_id found in each purchase_price"
      - name: ship
        identifier: raw_gz_ship
        description: "sales of Greenweez / we have one row per orders_id found in each shipping_fees"

models:
  - name: stg_gz_raw_data__product
    columns:
      - name: product_id   # ou products_id si c’est ton nom final
        tests:
          - not_null
          - unique

  - name: stg_gz_raw_data__ship
    columns:
      - name: orders_id
        tests:
          - not_null
          - unique

  - name: stg_gz_raw_data__sales
    columns:
      - name: orders_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [orders_id, product_id]